version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db_definder_api
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123dimas
      POSTGRES_DB: definder
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d definder"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: definder_api
    restart: unless-stopped
    environment:
      PORT: "8080"
      DB_CONNECTION: "postgres"
      DB_HOST: "db"
      DB_DATABASE: "definder"
      DB_USERNAME: "developer"
      DB_PASSWORD: "123dimas"
      JWT_SECRET_KEY: "secret"
      JWT_EXPIRATION: "1hr"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
